# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_REGION: us-central1
  _AR_REPO: jobs-preopt
  _IMAGE_NAME: preopt
  _TAG: $SHORT_SHA

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - ${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}
      - ${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:latest

images:
  - ${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}
  - ${_AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_IMAGE_NAME}:latest
